language: python

python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install --use-mirrors -r requirements.txt
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=pyslash

after_success:
  - coveralls
