language: python

python:
  - 3.5
  - 3.6

install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
  - pipenv install coveralls

script:
  - pipenv run nosetests --with-coverage --cover-package=pyslash

after_success:
  - pipenv run coveralls
