language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install coveralls

script:
  - pipenv run nosetests --with-coverage --cover-package=pyslash

after_success:
  - pipenv run coveralls
